package wallet.view.vistas;

/**
 *
 * @author Fernanda
 */
import wallet.dao.impl.TransaccionDAO;
import wallet.model.entity.Transaccion;
import wallet.view.components.Button;

import java.util.List;

import javax.swing.table.DefaultTableModel;

public class MisTransaccionesView extends javax.swing.JPanel {

    private TransaccionDAO dao;
    private int idUser;

    public MisTransaccionesView(int idUser) {
        this.idUser = idUser;
        initComponents();
        dao = new TransaccionDAO();
        cargarTransacciones();


    }
    private void cargarTransacciones() {
        List<Transaccion> transacciones = dao.listarTransacciones(idUser); // Obtén las transacciones del usuario con ID 1
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0); // Limpia la tabla

        for (Transaccion t : transacciones) {
            modelo.addRow(new Object[] {
                t.getFecha() ,t.getResumen()            
            });
        }
    }

    public Button getBackButton() {
        return BackButton;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        tituloLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BackButton = new Button();

        setBackground(new java.awt.Color(255, 255, 255));

        tituloLabel.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(182, 183, 192));
        tituloLabel.setText("Mis transacciones");

        jTable1.setRowHeight(25);
        jTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {}
                                        ,
                new String[] {
                        "Fecha", "Resumen"
                }));
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        BackButton.setText("Volver");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(103, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addComponent(tituloLabel)
                                                .addGap(347, 347, 347))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 693,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(97, 97, 97)))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tituloLabel)
                                .addGap(72, 72, 72)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                //.addGap(18,18,18)
                                //.addComponent(BackButton)
                                .addContainerGap(228, Short.MAX_VALUE)));
    }// </editor-fold>

    // Variables declaration - do not modify
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel tituloLabel;
    private Button BackButton;
    // End of variables declaration
}
